version: '3.5'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile

    ports: 
      - 81:80
    volumes:
      - ./src:/var/www/html/
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/Payments.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080